name: CI/CD
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CD
        run: cd /var/www/html/
      - name: Git Reset
        run: git reset --hard origin/master

      - name: Git Pull
        run: git pull origin master

      - name: Validate
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
